id: I6465777A
default_language: sa
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 14:40:38.088747
last_modified: 2023-02-09 14:40:38.088883
source_metadata:
  title: 'BA: Daśabhūmikasūtra'
  language: sa
bases:
  CEC4:
    base_file: CEC4.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
